from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from mysql import connector


class Ui_MainWindow(object):
    def __init__(self):
        self.my_database = connector.connect(user="root", password="881995sj", database="classmanagement")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.MainMenu.setGeometry(QtCore.QRect(40, 80, 931, 591))
        self.MainMenu.setDocumentMode(False)
        self.MainMenu.setTabsClosable(False)
        self.MainMenu.setTabBarAutoHide(False)
        self.MainMenu.setObjectName("MainMenu")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Login)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 110, 231, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.verticalLayout_2.addWidget(self.login_label)
        self.id_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.id_field.setObjectName("id_field")
        self.verticalLayout_2.addWidget(self.id_field)
        self.pass_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.verticalLayout_2.addWidget(self.pass_label)
        self.pass_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pass_field.setObjectName("pass_field")
        self.verticalLayout_2.addWidget(self.pass_field)
        self.logi_btn = QtWidgets.QPushButton(self.Login)
        self.logi_btn.setGeometry(QtCore.QRect(190, 300, 91, 31))
        self.logi_btn.setObjectName("logi_btn")
        self.MainMenu.addTab(self.Login, "")
        self.professorLogin = QtWidgets.QWidget()
        self.professorLogin.setObjectName("professorLogin")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.professorLogin)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(320, 50, 231, 396))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.id_register_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.id_register_label.setFont(font)
        self.id_register_label.setObjectName("id_register_label")
        self.verticalLayout_3.addWidget(self.id_register_label)
        self.id_register_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.id_register_field.setObjectName("id_register_field")
        self.verticalLayout_3.addWidget(self.id_register_field)
        self.pass_register_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pass_register_label.setFont(font)
        self.pass_register_label.setObjectName("pass_register_label")
        self.verticalLayout_3.addWidget(self.pass_register_label)
        self.password_register_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.password_register_field.setObjectName("password_register_field")
        self.verticalLayout_3.addWidget(self.password_register_field)
        self.confirm_pass_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.confirm_pass_label.setFont(font)
        self.confirm_pass_label.setObjectName("confirm_pass_label")
        self.verticalLayout_3.addWidget(self.confirm_pass_label)
        self.confirm_pass_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.confirm_pass_field.setObjectName("confirm_pass_field")
        self.verticalLayout_3.addWidget(self.confirm_pass_field)
        self.phone_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.verticalLayout_3.addWidget(self.phone_label)
        self.phone_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.phone_field.setObjectName("phone_field")
        self.verticalLayout_3.addWidget(self.phone_field)
        self.email_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.verticalLayout_3.addWidget(self.email_label)
        self.email_field = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.email_field.setObjectName("email_field")
        self.verticalLayout_3.addWidget(self.email_field)
        self.email_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.email_label_2.setFont(font)
        self.email_label_2.setObjectName("email_label_2")
        self.verticalLayout_3.addWidget(self.email_label_2)
        self.birth_date = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.birth_date.setObjectName("birth_date")
        self.birth_date.setCalendarPopup(True)
        self.verticalLayout_3.addWidget(self.birth_date)
        self.file_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.file_name_label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.file_name_label.setFont(font)
        self.file_name_label.setText("")
        self.file_name_label.setObjectName("file_name_label")
        self.verticalLayout_3.addWidget(self.file_name_label)
        self.register_btn = QtWidgets.QPushButton(self.professorLogin)
        self.register_btn.setGeometry(QtCore.QRect(390, 500, 93, 28))
        self.register_btn.setObjectName("register_btn")
        self.upload_file_btn = QtWidgets.QPushButton(self.professorLogin)
        self.upload_file_btn.setGeometry(QtCore.QRect(390, 460, 93, 28))
        self.upload_file_btn.setObjectName("upload_file")
        self.MainMenu.addTab(self.professorLogin, "")
        self.adminLogin = QtWidgets.QWidget()
        self.adminLogin.setObjectName("adminLogin")
        self.MainMenu.addTab(self.adminLogin, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.upload_file_btn.clicked.connect(self.upload_file)
        self.register_btn.clicked.connect(self.submit)

        self.retranslateUi(MainWindow)
        self.MainMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def upload_file(self):
        picture_path, _ = QFileDialog.getOpenFileName(caption='Open file', initialFilter="Image files (*.jpg)",
                                                      filter="Image files (*.jpg)")
        self.file_name_label.setText(picture_path)

    def submit(self):
        with open(self.file_name_label.text(), "rb") as file:
            result = file.read()
            file.close()
        mycursor = self.my_database.cursor(prepared=True)
        query = "CALL classmanagement.insert_student(%s, %s, %s, %s,%s, %s, %s, %s)"
        value = ("trungtest", self.id_register_field.text(), self.confirm_pass_field.text(), self.phone_field.text(),
                 self.email_field.text(), self.birth_date.text(), 1, result)
        mycursor.execute(query, value)
        self.my_database.commit()
        print("Success")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "ID:"))
        self.pass_label.setText(_translate("MainWindow", "Password"))
        self.logi_btn.setText(_translate("MainWindow", "Login"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.Login), _translate("MainWindow", "Login"))
        self.id_register_label.setText(_translate("MainWindow", "ID:"))
        self.pass_register_label.setText(_translate("MainWindow", "Password"))
        self.confirm_pass_label.setText(_translate("MainWindow", "Confirm Password"))
        self.phone_label.setText(_translate("MainWindow", "Phone"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.email_label_2.setText(_translate("MainWindow", "Date of birth"))
        self.register_btn.setText(_translate("MainWindow", "Sumit"))
        self.upload_file_btn.setText(_translate("MainWindow", "Upload File"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.professorLogin), _translate("MainWindow", "Register"))
        self.MainMenu.setTabText(self.MainMenu.indexOf(self.adminLogin), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
